Repository LimaInc/Gnome-Anns-Sky, pull requests merged in 2018-03, with the labels that each got.

#80 Ice generation
  Images/Blocks/ice.png
  Images/Blocks/ice.png.import
  Images/Items/itemIce.png
  Images/Items/itemIce.png.import
  Scripts/Blocks/IceBlock.cs
  Scripts/Fossils/Defossiliser.cs
  Scripts/Game.cs
  Scripts/Inventory/ItemStorage.cs
  Scripts/World/WorldGenerator.cs
  SustainableCraft.csproj
Labels: feature

#87 Improved chunk generation (ish)
  Scripts/Util/HashQueue.cs
  Scripts/World/Terrain.cs
  SustainableCraft.csproj
Labels: bug

#86 Improved block breakable code
  Scripts/Blocks/Block.cs
  Scripts/Blocks/DefossiliserBlock.cs
  Scripts/Blocks/FossilBlock.cs
  Scripts/Blocks/GrassBlock.cs
  Scripts/Blocks/HabitationBlock.cs
  Scripts/Blocks/IceBlock.cs
  Scripts/Blocks/LeafBlock.cs
  Scripts/Blocks/RedRock.cs
  Scripts/Blocks/Stone.cs
  Scripts/Blocks/TreeBlock.cs
  Scripts/Game.cs
  Scripts/Interaction.cs
Labels: enhancement

#88 Fixed sun position
  Scenes/MainScene.tscn
  Scripts/World/Sun.cs
  SustainableCraft.csproj
Labels: bug

#89 Player and inventory
  Scripts/Fossils/Defossiliser.cs
  Scripts/Fossils/DefossiliserAction.cs
  Scripts/GUI/GUIObjects/GUIFloatingSlot.cs
  Scripts/GUI/GUIObjects/GUIInventorySlot.cs
  Scripts/GUI/GUIObjects/GUIInventorySlotArray.cs
  Scripts/GUI/GUIObjects/GUILabeledSlotArray.cs
  Scripts/GUI/GUIObjects/GUIVerticalBar.cs
  Scripts/GUI/GUIStandalone/DefossiliserGUI.cs
  Scripts/GUI/GUIStandalone/InventoryGUI.cs
  Scripts/GUI/GUIStandalone/PlayerGUI.cs
  Scripts/Game.cs
  Scripts/Interaction.cs
  Scripts/Inventory/Inventory.cs
  Scripts/Inventory/Item.cs
  Scripts/Inventory/ItemBacteriaVial.cs
  Scripts/Inventory/ItemBlock.cs
  Scripts/Inventory/ItemConsumable.cs
  Scripts/Inventory/ItemDrink.cs
  Scripts/Inventory/ItemFood.cs
  Scripts/Inventory/ItemID.cs
  Scripts/Inventory/ItemPlant.cs
  Scripts/Inventory/ItemStack.cs
  Scripts/Inventory/ItemStorage.cs
  Scripts/Plants/GrassManager.cs
  Scripts/Plants/Plants.cs
  Scripts/Player.cs
  Scripts/World/Base.cs
  Scripts/World/Chunk.cs
  Scripts/World/Terrain.cs
  Scripts/World/WorldGeneration/WorldGenerator.cs
  SustainableCraft.csproj
  project.godot
Labels: enhancement

#97 Fixed shadow lighting bug
  Scenes/MainScene.tscn
Labels: bug

#110 Fixed shadows again
  Scenes/MainScene.tscn
Labels: bug

#109 Fix texture leaks
  Scripts/Util/TextureManager.cs
  models/big0/big.dae.import
  models/big1/big.dae.import
  models/frog0/frog.dae.import
  models/frog1/frog1.dae.import
  models/pig0/pig.dae.import
  models/pig1/pig1.dae.import
Labels: bug

#141 Increased shadow bias
  Scenes/GameplayScene.tscn
Labels: For presentation, bug
